### PR TITLE
allow entries to be functions

### PR DESCRIPTION
**Pull request by shellscape**
- [x] This is a **bugfix**
- [ ] This is a new **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **typo fix**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

Supersedes #32, fixes webpack/webpack#6718.

According to https://webpack.js.org/configuration/entry-context/#entry, entries can also be functions. hot-client didn't previously account for that, adding neither the client scripts nor validating the entry function result.

### Breaking Changes

None

### CODE REVIEW

**Comment by ndelangen** [comment]
When will this be released? 🙇

**Comment by shellscape** [comment]
@ndelangen hoping for later today, tomorrow at latest.

**Comment by ndelangen** [comment]
thank you kind sir 🙇

**Comment by shellscape** [comment]
@ndelangen looks like this went out in 2.1.0

**Pull request merged**
