### PR TITLE
Only include min version of loglevelnext to prevent CSP issues

### PR DESCRIPTION
**Pull request by kurtextrem**
Fixes shellscape/loglevelnext#2

- [x] This is a **bugfix**

### For Bugs and Features; did you add new tests?

No. The change is small enough.

### Motivation / Use-Case

See https://github.com/shellscape/loglevelnext/issues/2

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR :beer: This one is tough - webpack-hot-client is intended to be used solely in a development environment in tandem with webpack-dev-middleware. So by default we want to serve up the development bundles for all aspects, including using the dev bundle of `loglevelnext`. On the other hand, it looks like using this to test a chrome extension (never thought of that one) is a thing. I also don't want to add rarely-used features to this module, like being able to switch between loglevelnext endpoints. So it's a pickle and will need more thought.

In the mean time, see if these solutions work for you, which would help with CSP beyond this module, (first two look promising, please let me know if they work):
- Create a development profile and disable CSP for that profile: https://github.com/cozy/cozy-stack/issues/649#issuecomment-304232560
- [Disable CSP Extension](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden?hl=en)
- http://brianmayer.com/2012/12/defeating-chromes-content-security-policy-header-via-a-chrome-extension/
- looks a bit hacky, but might work https://www.youtube.com/watch?v=WiiboUWXyEY

**Comment by kurtextrem** [comment]
I see your conflict.
Anyway, I personally went with the solution in the PR, I've modified the file directly in my node_modules folder.

**Comment by shellscape** [comment]
I'd recommend seeing if that chrome extension and profile trick work first - that'd prevent you from running into the same situation with other modules in the future.

**Comment by kurtextrem** [comment]
Chrome does not have "about:config". Other extensions can't influence other Chrome extension's settings page (I even think they can't influence other extensions at all).

So, I've researched a little further and this seems to be the solution - add this to `manifest.json`:
`"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",`

(note the `unsafe-eval`)

PR can be closed I'd say :)

**Comment by shellscape** [comment]
Wonderful! Thanks for posting the solution, that's sure to help others. 🍻

**Pull request closed without merging**
