### PR TITLE
fix: https option for https.Server

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

An issue was raised in https://github.com/webpack-contrib/webpack-serve/issues/162 that there are shenanigans afoot in the module with regard to the `https` option not creating the correct result int he browser.

### Breaking Changes

None

### Additional Info

I found this to be the result of the WebSocket Server using a plain `http.Server` in the situation in which an https cert/key or pass/pfx pair is passed to `webpack-serve`. That's because the `ws` WebSocket Server will only run on an https server _if a listening server instance is passed to it_. In the situation in which a server instance is not passed, the `https` option should not be set.

In addition, this module will now set `https = true` if a `server` is passed and it's an instance of `https.Server`, and `https` hasn't already been set. That criteria is used as there may be a whacky situation we can't predict that someone may want to pass an `https.Server` but still need `https` to be `false`.

### CODE REVIEW

**Comment by bennidhamma** [comment]
@shellscape, my apologies for being so dense, I've pulled the webpack-serve code down, and am looking at the webpack-hot-client code, and the koa-webpack code, and I am just not following the trail of how the server gets instantiated. 

It looks like there are 2 different servers running in my current configuration, one is http, and one is https. Here is my webpack serve config section:

```javascript
  serve: {
    clipboard: false,
    host: '0.0.0.0',
    port: 3001,
    https: {
      key: sslKey,
      cert: sslCert,
    },
    hotClient: {
      port: 4430,
      // https: true,
      host: {
        server: '0.0.0.0',
        client: 'ben.maven.io'
      }
    },
    devMiddleware: {
      publicPath: '/dist/',
    },
    logLevel: 'debug'
  },
```

and when I curl on port 3001 and 4430 (showing with and without https), I seem to be getting two different protocols:

```
$ curl -k https://ben.maven.io:3001
Not Found 
$ curl -k https://ben.maven.io:4430
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
$ curl http://ben.maven.io:3001
curl: (52) Empty reply from server 
$ curl http://ben.maven.io:4430
Upgrade Required
```

**Comment by shellscape** [comment]
You're not being dense at all. In fact, you've arrived at the correct answer. A WebSocket Server does not need to be an instance of `https.Server` to communicate with a browser/client that is served from an `https.Server`. The `wss` protocol is only required (and by extension the `https` option) if an `https.Server` instance was passed to `webpack-hot-client` via the `server` option. 

Now, one might ask: why the hell is that option even there? Valid question in the context of `webpack-serve`, but `hot-client` can be used independently, and I have seen people using it in that way.

**Comment by Rodeoclash** [comment]
Looks like 4.0.4 is the release that contains this fix. Thanks for the speed on getting released.

**Comment by bennidhamma** [comment]
@shellscape you say 

>A WebSocket Server does not need to be an instance of https.Server to communicate with a browser/client that is served from an https.Server

Can you clarify what you mean by this? It's my understanding that if a browser has loaded a document via https, then websockets will also need to be secure.

Thank you! And thank  you for your quick fixes, and helpful explanations :)

**Comment by shellscape** [comment]
🙇  no worries, I do what I can, with everyone's help and enthusiasm.

> It's my understanding that if a browser has loaded a document via https, then WebSockets will also need to be secure.

I have not found the same to be true _if and only if_ the server handling WebSocket requests is not also configured for https/ssl. Since `ws://` or `wss://` is a separate protocol for a separate request to another server, it's cool. Here's a really bad diagram to show the request path:

```
[ https server ] ← browser ← assets / html / css / js
                                    ↓
                      client WebSocket
                                 ↙
[ ws http server ]  
```

Now say that the content/web server and WebSocket server were the same instance:

```
[ https server ] ← browser ← assets / html / css / js
                    ↖            ↓
                      client WebSocket
```

In this case, the protocol **_must_** be `wss://` since the server handling the request for WebSockets is tls/ssl/http.

**Comment by bennidhamma** [comment]
Hmmm.... This is the error message I get when I have a document loaded via https request an unsecure socket:

socket.js:19 Mixed Content: The page at 'https://ben.maven.io/testing/general' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://ben.maven.io:4430/'. This request has been blocked; this endpoint must be available over WSS.

socket.js:19 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

selection_011

From my research, I have not been able to find any examples of people serving content securely that are able to connect unsecure web sockets. Up until a few years ago, I believe Chrome had a flag that you could enable that would allow the mixed mode serving, but I believe they've since removed that configuration for security reasons.

**Comment by shellscape** [comment]
The test app at `/test/app/https` works in that scenario.

**Comment by bennidhamma** [comment]
okay I'll take a look!

**Comment by shellscape** [comment]
We may well find that passing-case is a half-truth, working only under `localhost`.

**Comment by bennidhamma** [comment]
I think you're right, the test does indeed work in Chrome, maybe it's localhost? I've tried it with our regular certs, and I've also tried it with the certs from `devcert`.

Firefox however, does throw a security exception:

selection_012

The spec seems *pretty* clear to me:

> 2. If secure is false but the origin of the entry script has a scheme component that is itself a secure protocol, e.g. HTTPS, then throw a SecurityError exception. (https://www.w3.org/TR/websockets/#the-websocket-interface)

Would you consider allowing the option to run the websockets through an http server?

**Comment by shellscape** [comment]
> Would you consider allowing the option to run the websockets through an http server?

I'm not sure I understand the question. The WebSocket server is already HTTP by default.

**Comment by bennidhamma** [comment]
Sorry, see my edit, meant to ask https

**Comment by Rodeoclash** [comment]
This is essentially where I'm at. We run `webpack-serve` with HTTPS and want to connect to a `wss://` backend to satisfy the browsers security requirements. While it's configured to ask for a `wss://` backend I believe it's actually serving a non SSL connection despite having the `wss://` prefix.

**Comment by shellscape** [comment]
Totally doable, but the right approach is needed. (Really I don't think the module has gotten use enough yet for this to come up at this need level, so it's good to see)

From a consumer's point of view, there needs to be a way to easily accomplish this setup. Since we already have a `server` property, which is meant for more advanced setups, this seems like the logical choice to rely on. From there, if `server instanceof https.Server` then the `https` property should automatically be set to `true`. The `ws` package used under the hood for this [works in much the same way](https://github.com/websockets/ws/blob/master/doc/ws.md), so there's some pass-through logic that lines up there.

That puts the onus of a correct configuration on the consumer then.

However, that has one major drawback. When attaching a WebSocket (`ws`) Server to an existing `https.Server`, that renders the `host` and `port` options for hot-client moot. That's going to mean that the consumer is going to have to spin up _two_ HTTPS servers if they want separate hosts and ports for content vs websockets: one for serving content/webpack bundles and the browser, and one for taking care of the SSL WebSocket connections.

**Comment by Rodeoclash** [comment]
Given the web socket is being served over SSL I think it would be a reasonable expectation that the content would be as well? If you mix SSL and non-SSL assets you'll get a number of browser warnings and (I'm not 100% sure on this) functionality that requires SSL to be enabled, w.g. WebRTC would cease to function.

What would suit our use case is that if the https block is present in the `webpack-serve` configuration, that all content (normal and ws) would be served using SSL from respective `https` and `wss://` endpoints.

**Comment by bennidhamma** [comment]
I tried creating my own httpServer and passing it into the hotClient section but when I started webpack-serve it just hung.

I definitely liked that approach well enough, once I went down the road. If something like that was the pattern I'd be thrilled.

Thank you @shellscape!

**Comment by shellscape** [comment]
@Rodeoclash I thought that was a given, and what we're talking about implementing here. Not sure you're following 🙃  It's not a question of _if_, it's a question of _how_ and good architecture now.

**Comment by Rodeoclash** [comment]
@shellscape Haha, clearly I'm not. Just being clear with exactly what my use case was.

I'll bow out and stop adding noise 😁

**Comment by bennidhamma** [comment]
I did call listen. It seemed like something wasn't competing because I wasn't getting any of the compile output from webpack. I'm AFK for the next few days, going on a canoe trip. So I'll have to check back in Monday. Thanks for all the help!

**Comment by shellscape** [comment]
@Rodeoclash not adding noise at all! Please do stick around, especially since this is directly related to your use-case.

**Comment by davejamesmiller** [comment]
I think I've run into the same issue as @bennidhamma. I want to run a secure (HTTPS / WSS) server to keep Chrome happy because I'm using a VM not `localhost`.

My first attempt was:

```
host: { client: 'dev.djm.me', server: '0.0.0.0' },
https: true,
```

But that actually runs a HTTP/WS server, so Chrome gives this error:

```
WebSocket connection to 'wss://dev.djm.me:8081/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
```

After digging through the code I realised it wasn't actually using the `https` option on the server side at all, only the client side, so I tried:

```
host: { client: 'dev.djm.me', server: '0.0.0.0' },
https: true,
server: new https.createServer({ key: ssl.serviceKey, cert: ssl.certificate }).listen(),
```

That makes the server run correctly, but it breaks the client - now the browser error says:

```
WebSocket connection to 'wss://[::]:37869/' failed: Error in connection establishment: net::ERR_ADDRESS_INVALID
```

It seems to ignore the `host.client` option when `server` is used. Specifically this code in index.js sets it to the server listening address (by default all interfaces, not a valid hostname):

```js
  if (options.server) {
    options.webSocket = {
      host: wss._server.address().address, // eslint-disable-line no-underscore-dangle
      port: wss._server.address().port // eslint-disable-line no-underscore-dangle
    };
  } else {
    options.webSocket = { host: host.client, port };
  }
```

If I change it to `host: host.client` then it works correctly for my particular case - but I'm not sure what the correct general solution is.

I also tried setting the listening address to the hostname:

```js
server: new https.createServer({ key: ssl.serviceKey, cert: ssl.certificate }).listen(0, 'dev.djm.me'),
```

But then it just hangs - I guess because the hostname isn't a valid interface it fails to start the server.

Finally, I tried setting the hostname to the IP address instead:

```js
server: new https.createServer({ key: ssl.serviceKey, cert: ssl.certificate }).listen(0, '192.168.5.3'),
```

Now it binds correctly, because it's a valid interface as well as a valid hostname, but then the SSL certificate isn't valid:

```
WebSocket connection to 'wss://192.168.5.3:42423/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID
```

I can live with that as a workaround because I can manually go to `https://192.168.5.3:42423/` and accept the certificate, but it would be good if there was an equivalent to the `host.client` option that works with the custom `server` option.

It would also be nice if `https: true` (without a custom `server`) actually created a HTTPS server instance rather than HTTP. (It might need to accept a cert & key as options, like [webpack-serve](https://github.com/webpack-contrib/webpack-serve#https) does.)

Alternatively, it would help to have a better explanation in the README of what the `https: true` option does and doesn't do, perhaps with an example of how to create a HTTPS server instance manually.

Let me know if there's anything I can do to help with any of that - I'm happy to make a PR for it as long as I know what direction you want to go.

Many thanks!

**Comment by bennidhamma** [comment]
I'm back from my canoe trip. Is there anything i can help with on this? Would you like me to give more detail / background on what happens when I try and create my own httpsServer and pass that in?

**Comment by d3viant0ne** [comment]
Generating local certs that actually work.
```
const fs = require('fs');
const selfsigned = require('selfsigned');
const attrs = [{ name: 'commonName', value: 'deviantjs.local' }];
const pems = selfsigned.generate(attrs, {
  algorithm: 'sha256',
  keySize: 2048,
  extensions: [
    {
      name: 'subjectAltName',
      altNames: [
        {
          type: 2, // DNS
          value: 'localhost',
        },
        {
          type: 2, // DNS
          value: 'deviantjs.local',
        },
        {
          type: 6, // URI
          value: 'https://deviantjs.local',
        },
        {
          type: 7, // IP
          ip: '127.0.0.1',
        },
      ],
    },
  ],
});

fs.writeFileSync('./.ssl/server.crt', pems.cert, { encoding: 'utf-8' });
fs.writeFileSync('./.ssl/server.key', pems.private, { encoding: 'utf-8' });
```

I'm running on the latest `webpack-serve@beta` with HMR over https and it works just fine in Chrome, Canary, Quantum and Edge.

**Comment by XEngine** [comment]
@d3viant0ne can you share your serve options?

**Pull request merged**
