### PR TITLE
fix: fixes #86, client port bungle

### LINKED ISSUE #86: Client port ignored
* Operating System: Alpine 3.7.0
* Node Version: 10.6.0
* NPM Version: 6.1.0
* webpack Version: 4.15.1
* webpack-hot-client Version: 4.1.0

### Expected Behavior

Websocket client uses client port.

### Actual Behavior

Websocket client try using server port.

### Code

```console
  $ webpack-serve docs/webpack.config.js
```

##### serve.config.js

```js
module.exports = {
  clipboard: false,
  devMiddleware: {
    publicPath: '/pattern-library/dist/'
  },
  hotClient: {
    allEntries: true,
    host: {
      client: '*',
      server: '127.0.0.1'
    },
    port: {
      client: 8082,
      server: 8081
    }
  },
  host: '0.0.0.0'
}
```

### How Do We Reproduce?

Set `hotClient.port` as an object with different ports for `client` and `server`.

I tracked the issue until [modifyCompiler](https://github.com/webpack-contrib/webpack-hot-client/blob/v4.1.0/lib/compiler.js#L129). `options.webSocket` changes between the function call and `beforeCompile` event. No idea why.

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fixes #86. Looks like the logic around spinning up servers and passed `port.client` values got a little bungled. 

### Breaking Changes

None

### Additional Info

None

### CODE REVIEW

**Comment by MatTheCat** [comment]
Now client port is rigtly used but I can't access the WebSocket server; don't know if it's related.

**Comment by shellscape** [comment]
Well changing the client port is only for people who have proxies in place to handle that scenario. If you've specified a different client port, you're going to have to make sure that your setup can support that. It's an advanced setting for specialized environments, and there's no way for the module to know if an environment is setup correctly to handle it.

**Comment by MatTheCat** [comment]
I think I don't understand `host.server`. Setting `127.0.0.1` or `localhost` didn't do the trick but `0.0.0.0` works :thinking:

**Comment by shellscape** [comment]
`host.server` is to setup the host on which the `WebSocket` server will bind to. It really depends on your environment setup (and whether or not there's a proxy/reverse proxy, etc) for what value to use there. If `0.0.0.0` works then you might have a setup issue with the environment you're running this stuff in.

**Comment by shellscape** [comment]
@MatTheCat back on topic though - the port issue you described is fixed with this PR though, yes?

**Comment by MatTheCat** [comment]
Okay using the docker container host works :tada: 

So the issue as indeed fixed.

**Pull request merged**
