### PR TITLE
feat: allEntries applies client entry to all entries

### LINKED ISSUE #60: README: client per entry vs single client per all entries
* Operating System: macOS 10.13.4
* Node Version: 8.10.0
* NPM Version: 5.80
* webpack Version: 4.8.2
* webpack-hot-client Version: 3.0.0

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Description

I am using `webpack-hot-client` together with `webpack-serve`. Now with version 3.0.0 being out and #53 and #58 merged, how can one configure webpack-hot-client to have a client per entry as opposed to only one client per all entries? Would be great to have it mentioned somewhere in the README

### PR DESCRIPTION
**Pull request by shellscape**
- [ ] This is a **bugfix**
- [x] This is a new **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **typo fix**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

#60 Raised a good point about limiting the auto-configure to just the first entry in a key:value object entry structure. This feature provides a means to apply auto-configure to all keys in an object entry, without having the manually do so.

### Breaking Changes

None

### Additional Info

Fixes #60

### CODE REVIEW

**Comment by aaronjensen** [comment]
@shellscape howdy, would you mind cutting a release of this when you have a chance, please? It'd be super helpful for us. Thanks!

**Comment by evilebottnawi** [comment]
@shellscape also wait new release :trollface:

**Comment by aaronjensen** [comment]
I'm sorry, I didn't mean to offend or to press (though I'm not sure it warranted patronizing). I was able to work around the issue by piecing together the workaround steps from the original issue. Thanks!

**Comment by shellscape** [comment]
@aaronjensen dude - way too sensitive. also a misuse of _patronizing_. dial it back a notch or two, there are no eggshells to walk on here.

**Comment by ooflorent** [comment]
@shellscape 😱 that was hard to understand for a foreigner!

**Comment by shellscape** [comment]
@ooflorent 😱

**Pull request merged**
